from .LBM_Relighting import NODE_CLASS_MAPPINGS as RELIGHTING_NODES
from .LBM_DepthNormal import NODE_CLASS_MAPPINGS as DEPTHNORMAL_NODES

# Merge all node mappings
NODE_CLASS_MAPPINGS = {
    **RELIGHTING_NODES,
    **DEPTHNORMAL_NODES
}

# Merge all display name mappings
from .LBM_Relighting import NODE_DISPLAY_NAME_MAPPINGS as RELIGHTING_DISPLAY_NAMES
from .LBM_DepthNormal import NODE_DISPLAY_NAME_MAPPINGS as DEPTHNORMAL_DISPLAY_NAMES

NODE_DISPLAY_NAME_MAPPINGS = {
    **RELIGHTING_DISPLAY_NAMES,
    **DEPTHNORMAL_DISPLAY_NAMES
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]